version: '3.9'

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
    command: server /data
    volumes:
      - minio-data:/data

volumes:
  minio-data:
